version: '3.8'
services:
  node01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: node01
    environment:
      - node.name=node01
      - cluster.name=es-cluster-7
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data01:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    networks:
      - es-network

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://node01:9200
    ports:
      - ${KIBANA_PORT}:5601
    networks:
      - es-network
    depends_on:
      - node01

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:${STACK_VERSION}
    container_name: metricbeat
    environment:
      ELASTICSEARCH_HOSTS: http://node01:9200
    volumes:
      - metricbeat-data01:/usr/share/metricbeat/data
    networks:
      - es-network
    depends_on:
      - node01

  master-1:
    depends_on:
      - kibana
    container_name: master-1
    build:
      context: ../../
      dockerfile: docker/elastic/centosstream9.Dockerfile
      target: master-1
    networks:
      es-network:
        aliases:
          - master-1
  minion-1:
    depends_on:
      - kibana
    container_name: minion-1
    build:
      context: ../../
      dockerfile: docker/elastic/centosstream9.Dockerfile
      target: minion-1
    networks:
      es-network:
        aliases:
          - minion-1
  minion-2:
    depends_on:
      - kibana
    container_name: minion-2
    build:
      context: ../../
      dockerfile: docker/elastic/centosstream8.Dockerfile
      target: minion-2
    networks:
      es-network:
        aliases:
          - minion-2
  master-2:
    depends_on:
      - kibana
    container_name: master-2
    build:
      context: ../../
      dockerfile: docker/elastic/debian11.Dockerfile
      target: master-2
    networks:
      es-network:
        aliases:
          - master-2
  minion-3:
    depends_on:
      - kibana
    container_name: minion-3
    build:
      context: ../../
      dockerfile: docker/elastic/debian11.Dockerfile
      target: minion-3
    networks:
      es-network:
        aliases:
          - minion-3
  minion-4:
    depends_on:
      - kibana
    container_name: minion-4
    build:
      context: ../../
      dockerfile: docker/elastic/debian10.Dockerfile
      target: minion-4
    networks:
      es-network:
        aliases:
          - minion-4

volumes:
  es-data01:
    driver: local
  metricbeat-data01:
    driver: local

networks:
  es-network:
    driver: bridge
